seed: 1234

trainer:
  gpus: 0
  overfit_batches: 0.0
  check_val_every_n_epoch: 1
  fast_dev_run: false
  max_epochs: 30
  min_epochs: 1
  num_sanity_val_steps: 0
  auto_lr_find: false

callbacks:
  model_checkpoint:
    save_top_k: 1
    save_weights_only: true
    mode: "min"
    monitor: "val/loss"
    filename: "lit_model"
  early_stopping:
    patience: 5
    mode: "min"
    monitor: "val/loss"

data:
  batch_size: 32
  num_workers: 0
  pin_memory: false
  num_train: 1000
  num_val: 200
  num_test: 200
  max_length: 5
  min_overlap: 0.0
  max_overlap: 0.4

lit_model:
  # Optimizer
  lr: 3e-4
  # Scheduler
  mode: "min"
  monitor: "val/loss"
  factor: 0.1
  patience: 2
  # To be updated during runtime
  padding_index: ???
  blank_index: ???

logger:
  project: "handwritten-multi-digit-number-recognition"